title: CV | Jumg Eun
description:  A beautiful template for your CV.
url: 'https://jjungeeun.github.io/cv/'
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
